import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

// 访问/时，auth会匹配到@auth/page.js
// 访问/login时，auth会匹配到@auth/login/page.js,
// 访问/about时，auth会匹配到@auth/default.js
export default function RootLayout({ children, auth }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <Link href="/login">Go to login</Link>
        </div>
        <div>
          <Link href="/">Home</Link>
        </div>
        <div>/app/layout.js</div>
        <div>{children}</div>
        <div>{auth}</div>
      </body>
    </html>
  )
}
