import './globals.css'
import Link from 'next/link'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* 在视口内的路由会prefetch预加载，并结合Router cache路由缓存, 似的路由切换很顺滑 */}
        <div className="text-red-400 bg-slate-600">
          <Link href="/a">Link to a</Link>
        </div>
        <div>
          <Link href="/b">Link to b</Link>
        </div>
        {children}
      </body>
    </html>
  )
}
