// 'use client' // 根布局不能是客户端组件
// 根布局(必需)
// 根布局必须包含html和body标签
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-red">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
