import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

/**
 * @开头定义的文件夹，是特殊的文件夹，跟路由组一样，不会影响URL,/@team/members对应是members, 匹配到的路由组件, 会作为props传递给统计的layout组件中
 * children其实就是一个隐式的插槽，同级的page.js可以看成是app/@children/page.js
 * 在方位/cart时会出现404， 因为此时team和analytics都是undefined, 此时要添加default.js， 作为team、analytics默认的路由组件
 */
export default function RootLayout({ children, team, analytics }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>{children}</div>
        <div>{team}</div>
        <div>{analytics}</div>
      </body>
    </html>
  )
}
