import { Bungee_Shade } from 'next/font/google'
import './globals.css'

const bungee_shade = Bungee_Shade({
  style: 'normal',
  subsets: ['latin', 'latin-ext'],
  weight: ['400']
})

export const metadata = {
  title: {
    default: 'Create Next App',
    template: '%s - Create Next App'
  },
  description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={bungee_shade.className}>{children}</body>
    </html>
  )
}
